name: RustCI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-n-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Maturin
      run: pip install maturin

    - name: Build Wheels
      run: maturin build
